import React, { useState } from 'react';
import { ScanResult } from '../types';
import { FileText, Download, Copy, Check, X, Printer, ShieldCheck } from 'lucide-react';

interface AuditReportExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  scanResult: ScanResult | null;
}

export const AuditReportExportModal: React.FC<AuditReportExportModalProps> = ({
  isOpen,
  onClose,
  scanResult,
}) => {
  const [copied, setCopied] = useState(false);
  const [exportFormat, setExportFormat] = useState<'markdown' | 'json'>('markdown');

  if (!isOpen || !scanResult) return null;

  const generateMarkdownReport = () => {
    const { metrics, issues, targetName, timestamp, executiveSummary, keyRisks, immediateActions } = scanResult;

    return `# Security Assessment & Vulnerability Audit Report
**Target:** \`${targetName}\`  
**Date:** ${new Date(timestamp).toUTCString()}  
**Security Score:** ${metrics.score}/100 (Grade: ${metrics.grade})  
**Analyzed Files:** ${metrics.filesAnalyzed} (${metrics.linesAnalyzed} lines)  

---

## 1. Executive Summary
${executiveSummary}

### Key Risk Areas:
${keyRisks.map((r) => `- ${r}`).join('\n')}

### Recommended Immediate Actions:
${immediateActions.map((a) => `- ${a}`).join('\n')}

---

## 2. Vulnerability Severity Metrics
- **Critical Severity:** ${metrics.criticalCount}
- **High Severity:** ${metrics.highCount}
- **Medium Severity:** ${metrics.mediumCount}
- **Low Severity:** ${metrics.lowCount}
- **Total Findings:** ${metrics.totalIssues}

---

## 3. Detailed Security Findings Inventory

${issues
  .map(
    (issue, i) => `### ${i + 1}. [${issue.severity}] ${issue.title}
- **File:** \`${issue.filePath}:${issue.startLine}\`
- **CWE:** ${issue.cwe || 'N/A'} (CVSS: ${issue.cvssScore || 'N/A'})
- **Description:** ${issue.description}
- **Exploitation Impact:** ${issue.impact}
- **Remediation:** ${issue.recommendation}

${
  issue.vulnerableSnippet
    ? `**Vulnerable Snippet:**
\`\`\`
${issue.vulnerableSnippet}
\`\`\`
`
    : ''
}
${
  issue.fixedSnippet
    ? `**Proposed Hardened Patch:**
\`\`\`
${issue.fixedSnippet}
\`\`\`
`
    : ''
}
`
  )
  .join('\n\n---\n\n')}

*Generated by AI Code Security Checker*
`;
  };

  const reportText =
    exportFormat === 'markdown'
      ? generateMarkdownReport()
      : JSON.stringify(scanResult, null, 2);

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const filename = `security-audit-${scanResult.targetName.replace(/[^a-zA-Z0-9_-]/g, '_')}.${
      exportFormat === 'markdown' ? 'md' : 'json'
    }`;
    const blob = new Blob([reportText], {
      type: exportFormat === 'markdown' ? 'text/markdown' : 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-3xl shadow-2xl flex flex-col max-h-[90vh]">
        {/* Modal Header */}
        <div className="p-5 border-b border-slate-800 flex items-center justify-between bg-slate-950">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-blue-600/20 border border-blue-500/40 flex items-center justify-center text-blue-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-100">Export Security Audit Report</h3>
              <p className="text-xs text-slate-400">Compliance & Executive DevSecOps Documentation</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <div className="flex items-center p-1 bg-slate-900 rounded-lg border border-slate-800 text-xs">
              <button
                onClick={() => setExportFormat('markdown')}
                className={`px-2.5 py-1 rounded-md transition-colors ${
                  exportFormat === 'markdown' ? 'bg-blue-600 text-white font-semibold' : 'text-slate-400'
                }`}
              >
                Markdown
              </button>
              <button
                onClick={() => setExportFormat('json')}
                className={`px-2.5 py-1 rounded-md transition-colors ${
                  exportFormat === 'json' ? 'bg-blue-600 text-white font-semibold' : 'text-slate-400'
                }`}
              >
                JSON
              </button>
            </div>

            <button
              onClick={onClose}
              className="text-slate-400 hover:text-white p-1 rounded-lg hover:bg-slate-800 cursor-pointer ml-2"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Body Preview */}
        <div className="p-5 flex-1 overflow-y-auto bg-slate-950/60 font-mono text-xs text-slate-300">
          <pre className="whitespace-pre-wrap leading-relaxed">{reportText}</pre>
        </div>

        {/* Modal Footer Actions */}
        <div className="p-4 border-t border-slate-800 bg-slate-950 flex flex-wrap items-center justify-between gap-3">
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3 py-2 bg-slate-900 hover:bg-slate-800 text-slate-300 text-xs font-medium rounded-xl border border-slate-800 transition-colors cursor-pointer"
          >
            <Printer className="w-4 h-4" />
            <span>Print Report</span>
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-2 bg-slate-900 hover:bg-slate-800 text-slate-300 text-xs font-medium rounded-xl border border-slate-800 transition-colors cursor-pointer"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              <span>{copied ? 'Copied' : 'Copy Text'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold rounded-xl shadow-lg shadow-blue-600/20 transition-colors cursor-pointer"
            >
              <Download className="w-4 h-4" />
              <span>Download {exportFormat.toUpperCase()}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
